name: deploy terraform

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'atlantis/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deployment:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Terraform-CI
        uses: docker/build-push-action@v5
        with:
          context: ./terraform
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/terraform-ci:latest
      - name: Atlantis
        uses: docker/build-push-action@v5
        with:
          context: ./atlantis
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/terraform-ci:atlantis
