name: deploy gh-actions

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'gh-actions/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deployment:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Actions Runner DinD
        uses: docker/build-push-action@v5
        with:
          context: ./gh-actions/actions-runner-dind
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/actions-runner-dind:latest
